version: '3'
services:
  # client:
  #   build: ./zipzap-web-client
  #   ports:
  #     - "5173:5173" # Change this if using another frontend framework (React, Vue, etc.)
  #   networks:
  #     - frontend
  #   depends_on:
  #     - api-gateway
  api-gateway:
    build: ./api-gateway
    restart: no
    hostname: api-gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  token-service:
    build: ./token-service
    restart: no
    hostname: token-service
    env_file:
      - .env
    networks:
      - backend
  users-service:
    build: ./users-service
    restart: no
    hostname: users-service
    env_file:
      - .env
    networks:
      - backend
  user-ratings-service:
    build: ./user-ratings-service
    restart: no
    hostname: user-ratings-service
    env_file:
      - .env
    networks:
      - backend
  jobs-service:
    build: ./jobs-service
    restart: no
    hostname: jobs-service
    env_file:
      - .env
    networks:
      - backend
  applications-service:
    build: ./applications-service
    restart: no
    hostname: applications-service
    env_file:
      - .env
    networks:
      - backend
  messages-service:
    build: ./messages-service
    restart: no
    hostname: messages-service
    env_file:
      - .env
    networks:
      - backend
  mongo:
    image: 'mongo:6'
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure